apiVersion: v1
kind: Service
metadata:
  name: laravel-ddd-service
spec:
  selector:
    app: laravel-ddd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
